version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres-antonio:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=antonio
      - POSTGRES_USER=antonio
      - POSTGRES_DB=antonio